In [31]:
#types of arrays
# 1. 1D array 
import numpy as np

a = [1, 2, 3, 4]

arr = np.array(a)

print("List in Python:", a)
print("NumPy Array in Python:", arr)

List in Python: [1, 2, 3, 4]
NumPy Array in Python: [1 2 3 4]


In [32]:
# checking the type of array
import numpy as np

list_1 = [1, 2, 3]

sample_array = np.array(list_1)

print(type(list_1))

print(type(sample_array))

<class 'list'>
<class 'numpy.ndarray'>


In [33]:
# multi-dimensional array
import numpy as np

list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]
list_3 = [9, 10, 11, 12]

sample_array = np.array([list_1,
                         list_2,
                         list_3])

print("Numpy multi dimensional array in python\n",
      sample_array)

Numpy multi dimensional array in python
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [34]:
# parameters of numpy array
# 1.axis
# 2.shape
import numpy as np

sample_array = np.array([[0, 4, 2],
                         [3, 4, 5],
                         [23, 4, 5],
                         [2, 34, 5],
                         [5, 6, 7]])

print("shape of the array :",
      sample_array.shape)

shape of the array : (5, 3)


In [35]:
# 4. Data Type Objects (dtype)
import numpy as np

sample_array_1 = np.array([[0, 4, 2]])

sample_array_2 = np.array([0.2, 0.4, 2.4])

print("Data type of the array 1 :",
      sample_array_1.dtype)

print("Data type of array 2 :",
      sample_array_2.dtype)

Data type of the array 1 : int64
Data type of array 2 : float64


In [36]:
# 5. numpy.array()
import numpy as np

arr = np.array([3, 4, 5, 5])

print("Array :", arr)
print("Type of the array :", type(arr))

Array : [3 4 5 5]
Type of the array : <class 'numpy.ndarray'>


In [37]:
# 6. numpy.fromiter()
import numpy as np

var = "Geekforgeeks"

arr = np.fromiter(var, dtype='U2')

print("fromiter() array :", arr)

fromiter() array : ['G' 'e' 'e' 'k' 'f' 'o' 'r' 'g' 'e' 'e' 'k' 's']


In [38]:
#  numpy.zeros()
import numpy as np

arr = np.zeros([4, 3],
               dtype=np.int32)

print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
